package com.toonflow.service.pipeline;

public enum PipelineState {
    PENDING,
    NOVEL_GENERATING, NOVEL_COMPLETE,
    STORYLINE_GENERATING, STORYLINE_COMPLETE,
    OUTLINE_GENERATING, OUTLINE_REVIEWING, OUTLINE_COMPLETE,
    ASSETS_EXTRACTING, ASSETS_IMAGE_GENERATING, ASSETS_COMPLETE,
    SCRIPT_GENERATING, SCRIPT_COMPLETE,
    STORYBOARD_GENERATING, STORYBOARD_COMPLETE,
    STORYBOARD_IMAGE_GENERATING, IMAGE_QUALITY_CHECKING, STORYBOARD_IMAGE_COMPLETE,
    TTS_GENERATING, TTS_COMPLETE,
    VIDEO_GENERATING, VIDEO_COMPLETE,
    COMPOSING, COMPOSE_COMPLETE,
    ALL_COMPLETE, STEP_FAILED
}
